# Generated by Django 5.0.4 on 2024-10-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profilepicture',
            field=models.ImageField(blank=True, null=True, upload_to='images/profilepictures'),
        ),
    ]
