# Generated by Django 5.0.4 on 2024-10-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_contact_alter_user_profilepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pw',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
