# Generated by Django 5.1 on 2024-10-02 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_pw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pw',
        ),
    ]
