# Generated by Django 5.0.4 on 2024-10-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_pw'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pwd',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
