# Generated by Django 5.1 on 2024-11-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_pwd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilepicture',
            field=models.ImageField(blank=True, default='images/profilepictures/rafid1.jpg', null=True, upload_to='images/profilepictures'),
        ),
    ]
