# Generated by Django 5.0.4 on 2024-11-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_event_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='code',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
    ]
