# Generated by Django 5.0.4 on 2024-11-19 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_event_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousUserPicsRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.picsrelation')),
            ],
        ),
    ]
