# Generated by Django 5.0.4 on 2024-11-19 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_anonymoususerpicsrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymoususerpicsrelation',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.event'),
        ),
    ]
