# Generated by Django 5.0.4 on 2024-10-02 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_user_contact_alter_user_profilepicture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_date', models.DateField()),
                ('guest', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='guest_events', to=settings.AUTH_USER_MODEL)),
                ('host', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='hosted_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('image', models.ImageField(upload_to='images/')),
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='PicsRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.picture')),
            ],
        ),
    ]
