# Generated by Django 5.0.4 on 2024-10-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.AutoField(default='', primary_key=True, serialize=False),
        ),
    ]
