# Generated by Django 5.1 on 2024-10-03 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_event_description_event_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='guests',
            new_name='guest',
        ),
    ]
