# Generated by Django 5.0.4 on 2024-10-03 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_event_eventpic_eventpicture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picsrelation',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='picsrelation',
            name='user',
        ),
        migrations.AddField(
            model_name='picsrelation',
            name='event',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='home.event'),
        ),
        migrations.AddField(
            model_name='picsrelation',
            name='image',
            field=models.ImageField(default='', upload_to='images/eventPictures'),
        ),
        migrations.DeleteModel(
            name='EventPicture',
        ),
    ]
