# Generated by Django 5.0.4 on 2024-10-03 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_event_event_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
