# Generated by Django 5.0.4 on 2024-10-04 18:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_delete_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='picsrelation',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
