# Generated by Django 5.0.4 on 2024-10-07 09:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_picsrelation_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='userPicsRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='images/UserPictures')),
                ('user', models.ManyToManyField(related_name='guest_pics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
