# Generated by Django 5.0.4 on 2024-10-07 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_userpicsrelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpicsrelation',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.picsrelation'),
        ),
    ]
