# Generated by Django 5.0.4 on 2024-10-17 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_userpicsrelation_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='guest',
        ),
    ]
