# Generated by Django 5.1 on 2024-10-03 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_alter_picture_uploader_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picsrelation',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='picsrelation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='uploader',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='PicsRelation',
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
